controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
    
ess_add:
    path: /ess/add
    controller: App\Controller\EssController::add
